module.exports = {
    UNDEFINED : "UNDEFINED", 
    ON_SCHEDULE : "ONSCHEDULE", 
    ON_TIME : "ONTIME",
    DELAYED : "DELAYED", 
    CANCELLED : "CANCELLED",
    FLIGHT_CANCELLED : "CD",
    FLIGHT_DEPARTED : "DP",
    FLIGHT_EARLY : "FE",
    FLIGHT_ON_TIME : "OT",
    FLIGHT_DELAYED : "DL",
    FLIGHT_NO_STATUS : "NA",
    FLIGHT_REROUTED : "RT",
    FLIGHT_LANDED : "LD"

};